### ISSUE TITLE
Chrome Not Found

### ISSUE THREAD

**Issue by EmirhaaNaN** [Flam3rboy/clickfarm#2]
Error: Google Chrome not found
    at Object.<anonymous> (C:\snapshot\clickfarm\dist\util\Browser.js:50:19)
    at Generator.next (<anonymous>)
    at C:\snapshot\clickfarm\dist\util\Browser.js:8:71
    at new Promise (<anonymous>)
    at C:\snapshot\clickfarm\dist\util\Browser.js:4:12
    at Object.getBrowser (C:\snapshot\clickfarm\dist\util\Browser.js:21:12)
    at Action.<anonymous> (C:\snapshot\clickfarm\dist\util\Action.js:57:67)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\clickfarm\dist\util\Action.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by Flam3rboy** [comment]
This project will be archived
